# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Chukot spellchecker"
ckt = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Chukot, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
ckt = "TRANSLATE: A spellchecker for Chukot, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ckt"

[windows]
system_product_code = "{A7C9FB67-D8AD-48BD-9453-346020B80312}_is1"
legacy_product_codes = [
    { value = "6F02B6CB-9AAA-4881-AF11-05990F25CDC2", kind = "nsis" },
    { value = "D292853C-A280-42E9-97BF-7E571EB7D877", kind = "nsis" }
]

[package.speller]
name = "Chukot"
version = "0.1.1"

[package.grammar]
name = "Chukot"
version = "0.1.0"

[package.tts-text-proc]
name = "Chukot"
version = "0.1.0"
